SerpentAudioGameAgentPlugin:
  frame_handler: PLAY
SerpentCombineGameAgentPlugin:
  frame_handler: PLAY
SerpentDasherGameAgentPlugin:
  frame_handler: PLAY
SerpentGeometryDashGamePlugin:
  fps: 30
SerpentRecorderGameAgentPlugin:
  frame_handler: PLAY
SerpentexitGamePlugin:
  fps: 30
